### ISSUE TITLE
Use newer version of grpc to get newer version of opencensus-api

### ISSUE THREAD

**Issue by pavelgajdos** [kubemq-io/kubemq-Java#11]
Hi, 

I need to use `com.google.api-client:google-api-client:1.32.1` which uses `com.google.http-client:google-http-client` which uses `io.opencensus:opencensus-api:0.28.0`

Your SDK uses `io.opencensus:opencensus-api:0.12.3` required by some `io.grpc` dependency. 

Gradle resolves the dependency to the newer version `io.opencensus:opencensus-api:0.28.0`.

When using your SDK with the latest version of `opencensus-api`, the problem is in usage of `io.opencensus.trace.unsafe.ContextUtils.CONTEXT_SPAN_KEY` which had been deprecated for some time and has been `private` since `io.opencensus:opencensus-api:0.24.0`.

See the difference of versions of `io.opencensus:opencensus-api` here:
- https://github.com/census-instrumentation/opencensus-java/blob/v0.23.x/api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java
- https://github.com/census-instrumentation/opencensus-java/blob/v0.24.x/api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java

I made it work with usage of `com.google.api-client:google-api-client:1.30.2`, however this version is from Jul 02, 2019, over 2 years old now.

Do you think it is possible to fix this?

Thank you and keep up the good work!

**Comment by liornabat** [comment]
We will check

**Comment by kubemq** [comment]
Deps were updated
