### ISSUE TITLE
How to use the Wildcards feature?

### ISSUE THREAD

**Issue by terry8yu** [kubemq-io/kubemq-Java#14]
When I use the code below to subscribe the events, it reported the error:
`SubscribeRequest subscribeRequest = new SubscribeRequest();
        subscribeRequest.setChannel("mqtt.>");
        subscribeRequest.setClientID("location-event");
        subscribeRequest.setSubscribeType(SubscribeType.EventsStore);
        subscribeRequest.setEventsStoreType(EventsStoreType.StartAtSequence);
        try {
            subscriber.SubscribeToEvents(subscribeRequest, this);
            log.info("[EventListener::init] Subscribe to events-store [channel name : {}] successfully.", subscribeRequest.getChannel());
        } catch (ServerAddressNotSuppliedException | SSLException e) {
            log.error("[EventListener::init] Failed to subscribe to events-store : ", e.getMessage());
            e.printStackTrace();
        }`
After the  subscriber.SubscribeToEvents, the onError reported:
io.grpc.StatusRuntimeException: INTERNAL: Error 107: invalid channel value, no wildcards are allowed.
Does it support the Wildcards feature, or otherwise?
Thx!
BTW: I use this SDK: io.kubemq.sdk:kubemq-sdk-Java:1.0.4.

**Comment by kubemq** [comment]
You cannot use * in Events-Store only on Events,
You can use our slack channel to ask questions

**Comment by terry8yu** [comment]
So you mean that Events-Store does not support *, does it support >?
Can I use > on Events?

**Comment by kubemq** [comment]
only on Events
no wildcards from any type is allowed on Events-Store

**Comment by terry8yu** [comment]
Got it, Thx!
