### ISSUE TITLE
RequestParameters class has no public constructors

### ISSUE THREAD

**Issue by Prev-I** [kubemq-io/kubemq-Java#15]
Trying to create a new RequestParameters class I've found that the class didn't have any public constructor.
Inside my IDE it reports the constructor as package-private (I'm using intellJ)

I've verified that in version 1.0.4, and inside the repository th public keyword is missing from both the constructors:

https://github.com/kubemq-io/kubemq-Java/blob/master/kubemq-java-sdk/src/main/java/io/kubemq/sdk/commandquery/RequestParameters.java

**Comment by kubemq** [comment]
Hi,
Issue was fixed in version v1.0.5
