### ISSUE TITLE
SDK is missing in the maven repository

### ISSUE THREAD

**Issue by C-Side** [kubemq-io/kubemq-Java#3]
I wanted to use the Java library for the KubeMQ but I'm unable to find the SDK in the maven repository.
The examples project under the following link is also gone: https://github.com/kubemq-io/kubemq-Java/tree/v1.0.1/examples

Kind regards,
Lukas

**Comment by stevehipwell** [comment]
I'm also wondering where the SDK is in the Maven repo!?

**Comment by gjermundgaraba** [comment]
Same here. A bit unsettling for using this for production when basic stuff like this is not here?

**Comment by Ido-Sheffer** [comment]
> Same here. A bit unsettling for using this for production when basic stuff like this is not here?
Please try to search it. 
https://search.maven.org/search?q=a:kubemq-sdk-Java

**Comment by stevehipwell** [comment]
@Ido-Sheffer I can see it has been re-published for maven but it looks like the version is incorrect? I would expect it to be 1.0.1 like the gradle version?

**Comment by Ido-Sheffer** [comment]
> @Ido-Sheffer I can see it has been re-published for maven but it looks like the version is incorrect? I would expect it to be 1.0.1 like the gradle version?

was updated to https://oss.sonatype.org/service/local/repositories/releases/content/io/kubemq/sdk/kubemq-sdk-Java/1.0.1/kubemq-sdk-Java-1.0.1.jar

**Comment by stevehipwell** [comment]
@Ido-Sheffer the version found in the central repository via search is still **0.1.6**. Could you explain why this is the case?

**Comment by Ido-Sheffer** [comment]
> @Ido-Sheffer the version found in the central repository via search is still **0.1.6**. Could you explain why this is the case?

oh sorry, I think it will take a few hours until the repository will be updated.

**Comment by stevehipwell** [comment]
Thanks @Ido-Sheffer it's updated now.

**Comment by nrheckman** [comment]
I just added a pull request to fix the README.
Correct dependency entry is:
` compile group: 'io.kubemq.sdk', name: 'kubemq-sdk-Java', version: '1.0.1'`
