### ISSUE TITLE
StreamObserver reconnect

### ISSUE THREAD

**Issue by veerapatyok** [kubemq-io/kubemq-Java#8]
How to restart StreamObserver(subscribe) when connect to KubeMQ fail or get error

thank you

**Comment by eitam-ring** [comment]
Hi @veerapatyok 
You will need to create a new Subscribe request

**Comment by veerapatyok** [comment]
Do they have a restart solution, document or detail to explain??

My solution is check with `Ping()`, when return error I create a new Subscribe request

**Comment by eitamring** [comment]
Please look at the following example:
https://github.com/kubemq-io/kubemq-Java/blob/FixTransaction/examples/src/main/java/io/kubemq/sdk/examples/get_Started/pubSub_Subscribe_to_a_Channel/Program.java

**Comment by eitam-ring** [comment]
Please look at the following example:
https://github.com/kubemq-io/kubemq-Java/blob/FixTransaction/examples/src/main/java/io/kubemq/sdk/examples/get_Started/pubSub_Subscribe_to_a_Channel/Program.java

**Comment by veerapatyok** [comment]
thank you
